#:schema taplo://taplo.toml

exclude = [".venv/**/*.toml"]
include = ["**/taplo.toml", "pyproject.toml"]

[formatting]
align_entries       = true
allowed_blank_lines = 1
column_width        = 80
compact_entries     = false
crlf                = false
indent_string       = "  "

[[rule]]
include = ["**/taplo.toml", "pyproject.toml"]

[rule.formatting]
reorder_arrays        = true
reorder_inline_tables = true
reorder_keys          = true

[[rule]]
exclude = ["pyproject.toml"]
keys    = ["project"]

[rule.formatting]
reorder_keys = false
